"""Write approximate late-preseason 2025 PPR ADP for retrospective scorecard."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "data" / "adp_2025.json"

# Approximate late-Aug / early-Sep 2025 PPR ADP consensus (Clay / CBS / FantasyPros blend).
# For hit-rate analysis vs actual 2025 finishes only — not live draft ADP.
ADP_2025 = {
    "Ja'Marr Chase": 1.5,
    "Bijan Robinson": 2.5,
    "Jahmyr Gibbs": 3.5,
    "Saquon Barkley": 4.5,
    "Christian McCaffrey": 5.5,
    "CeeDee Lamb": 6.5,
    "Justin Jefferson": 7.5,
    "Puka Nacua": 8.5,
    "Amon-Ra St. Brown": 9.5,
    "Jaxon Smith-Njigba": 10.5,
    "Nico Collins": 11.5,
    "Brian Thomas Jr.": 12.5,
    "Ashton Jeanty": 13.5,
    "Drake London": 14.5,
    "Jonathan Taylor": 15.5,
    "De'Von Achane": 16.5,
    "Malik Nabers": 17.5,
    "Bucky Irving": 18.5,
    "A.J. Brown": 19.5,
    "Chase Brown": 20.5,
    "Derrick Henry": 21.5,
    "Tetairoa McMillan": 22.5,
    "Josh Jacobs": 23.5,
    "Tee Higgins": 24.5,
    "Ladd McConkey": 25.5,
    "Breece Hall": 26.5,
    "Kyren Williams": 27.5,
    "Omarion Hampton": 28.5,
    "Trey McBride": 29.5,
    "Brock Bowers": 30.5,
    "Tyreek Hill": 31.5,
    "James Cook": 32.5,
    "Kenneth Walker III": 33.5,
    "DJ Moore": 34.5,
    "Garrett Wilson": 35.5,
    "Mike Evans": 36.5,
    "Marvin Harrison Jr.": 37.5,
    "DK Metcalf": 38.5,
    "Terry McLaurin": 39.5,
    "George Pickens": 40.5,
    "Zay Flowers": 41.5,
    "Josh Allen": 42.5,
    "Jaylen Waddle": 43.5,
    "Lamar Jackson": 44.5,
    "Alvin Kamara": 45.5,
    "Jayden Daniels": 46.5,
    "Chris Olave": 47.5,
    "Joe Burrow": 48.5,
    "Isiah Pacheco": 49.5,
    "Jalen Hurts": 50.5,
    "Rome Odunze": 51.5,
    "Sam LaPorta": 52.5,
    "Courtland Sutton": 53.5,
    "James Conner": 54.5,
    "Quinshon Judkins": 55.5,
    "Chuba Hubbard": 56.5,
    "David Montgomery": 57.5,
    "Travis Kelce": 58.5,
    "Jameson Williams": 59.5,
    "Rhamondre Stevenson": 60.5,
    "Xavier Worthy": 61.5,
    "Mark Andrews": 62.5,
    "Rashee Rice": 63.5,
    "Patrick Mahomes": 64.5,
    "Jordan Addison": 65.5,
    "Khalil Shakir": 66.5,
    "D'Andre Swift": 67.5,
    "Calvin Ridley": 68.5,
    "George Kittle": 55.0,
    "Emeka Egbuka": 70.5,
    "Javonte Williams": 71.5,
    "Stefon Diggs": 72.5,
    "Drake Maye": 74.5,
    "Josh Downs": 75.5,
    "Caleb Williams": 78.5,
    "Tony Pollard": 79.5,
    "Bo Nix": 80.5,
    "Justin Herbert": 82.5,
    "Baker Mayfield": 85.5,
    "Cam Skattebo": 86.5,
    "Tyler Warren": 88.5,
    "Tucker Kraft": 90.5,
    "David Njoku": 92.5,
    "Colston Loveland": 95.5,
    "Davante Adams": 33.0,
    "DeVonta Smith": 40.0,
}

payload = {
    "season": 2025,
    "scoring": "ppr",
    "updated": "2026-08-24",
    "note": (
        "Approximate late-preseason 2025 PPR ADP consensus for retrospective "
        "hit-rate analysis only. Not used in live 2026 rankings."
    ),
    "adp": ADP_2025,
}

OUT.write_text(json.dumps(payload, indent=2), encoding="utf-8")
print(f"Wrote {len(ADP_2025)} ADP entries → {OUT}")
